### ISSUE TITLE
Error in UseMethod("errors)

### ISSUE THREAD

**Issue by wetlandscapes** [r-quantities/errors#32]
Hi,
I was just playing around with the package, and came across the `lm()` example in the vignette and thought I'd play around with the functionality. When using `summary()` on the result, I get the following error:

```
Error in UseMethod("errors") : 
  no applicable method for 'errors' applied to an object of class "character"
In addition: Warning message:
In printCoefmat(coefs, digits = digits, signif.stars = signif.stars,  :
  NAs introduced by coercion
```

The error does not appear to impact the results, but it is curios.

Here is a minimal reprex for data in both a vector and dataframe format (I thought that might matter, but it doesn't):

```
library(errors)

#Generate data
set.seed(20190524)
x <- rnorm(1:5, 1:5, sd = 0.1)
y <- runif(5, 0, 10)

#Set errors
x <- set_errors(x, 0.01)
y <- set_errors(y, 0.05)

#Fit and summarize the data
lm_vector <- lm(y ~ x)
summary(lm_vector) #Error

#Fit and summarize the data, but as a dataframe. Any difference in behavior? No.
lm_df <- lm(y ~ x, data = data.frame(x, y))
summary(lm_df) #Error
```

Anyway, just wanted to let you know. Thanks for the really interesting package, by the way!

**Comment by Enchufa2** [comment]
This is to be expected. If you are referring to [this blog post](https://www.r-spatial.org/r/2018/08/31/quantities-final.html#fitting-linear-models-with-quantities), we explore there some possible ways to make quantities compatible with linear models, but this has not been addressed yet.
