### ISSUE TITLE
feature request - support for data.table

### ISSUE THREAD

**Issue by iembry** [r-quantities/errors#34]
Hi, I would like to request that in addition to data.frames, tibbles, etc. that you also have support for data.tables in future versions.

Thank you.

Irucka

**Comment by Enchufa2** [comment]
That would be great, but unfortunately, there's nothing we can do on our side. See, e.g., what happens in a simple subset:

```r
library(errors)
library(tibble)
library(data.table)

df <- tibble(x = set_errors(1:10, 0.1))
unclass(df[1,][[1]])
#> [1] 1
#> attr(,"id")
#> <environment: 0x5589e8403598>
#> attr(,"errors")
#> [1] 0.1
unclass(as.data.table(df)[1,][[1]])
#> [1] 1
#> attr(,"id")
#> <environment: 0x5589e826c708>
#> attr(,"errors")
#>  [1] 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
```

Tibbles work just like data frames, which means that they apply R operators to individual columns. The `errors` class has an implementation of the subsetting operator that also subsets the `errors` attribute, and thus we see the correct output.

On the other hand, `data.table` has its own way to store and work with columns. It's very efficient, but it does not forward standard calls like this. Attributes are copied over, but `[.errors` is never called, and this results in a corrupted `errors` object.

So the request would be the other way around: it would be nice if `data.table` (and also `dplyr`) could be more class-aware and attribute-friendly. But it's not a trivial task.

**Comment by iembry** [comment]
@Enchufa2  OK. Thank you for the detailed explanation. I'll use a `data.frame` rather than a `data.table` to store the errors.
