### ISSUE TITLE
Error in as.environment(pos) : invalid 'pos' argument

### ISSUE THREAD

**Issue by charvey23** [r-quantities/errors#41]
Hi, sorry to post again. I am running my code looping through each experiment and it is randomly throwing the following error when doing different operations ranging from addition to multiplication:

```
Error in as.environment(pos) : invalid 'pos' argument
In addition: Warning message:
In rm(list = id, pos = ht[[var]]) :
  object '<environment: 0x10d3a9438>' not found
```
Weirdly, if I by hand re-run each line of that case it does not throw the error and all input error and correlation numbers seem to be within reason. But it has been requiring manual interception to keep the loop running. Do you have any suggestions about what could be the issue?

**Comment by Enchufa2** [comment]
Could you provide a minimal snippet that reproduces the error?

**Comment by charvey23** [comment]
My apologies for the slow response. I can't seem to isolate a case that recreates the issue and at this point I am not able to share my full code and data. In my code for each iteration I read in ~18 variables with 12 of them being correlated to each other. I then perform multiple additions and multiplications and save the outputs into a dataframe. This then repeats 700 times. The error only occurs when iterating and not when the cases are run one at a time. From what I can tell the error happens in the "correl" function but it seemed to be very random when/if this would happen. It is potentially just some sort of memory issue in this case although it does happen on both my laptop and desktop. When it breaks I just re-run that iteration and no errors are raised. The results are also repeatable so I don't believe it is hurting the functionality. 
Sorry to have raised the issue without a clean issue for debugging please feel free to close this and if I can get a repeatable case I will reach out.

**Comment by Enchufa2** [comment]
Thanks. I know where the error happens, but I have no clue why and how. Could you please run `sessionInfo()` after the error and paste the output here? Does this happen for sequential execution, or are you using some kind of parallelisation? If you could share just the loop, with generic variable names, it may help to reproduce the issue with synthetic data.

**Comment by Enchufa2** [comment]
I have a suspicion. Could please install the following branch and re-run your code to see whether this version solves the issue?

```r
remotes::install_github("r-quantities/errors", "fix/41")
```

**Comment by charvey23** [comment]
I've installed the fix and unfortunately the same error occurred although much less frequently - stopping after 101 iterations rather than 22 for the first time though it does happen randomly so it's hard to know for sure. 
In the browser session I used sessionInfo() and have attached that output below. I am just doing this in a simple sequential for loop, no parallelization. I am not able to share the loop with generic variables as it is basically the whole file and making things generic would take a lot of time. The first error occurred while performing the 6th element matrix multiplication where I am multiplying the calibration matrix (of constants) by each of the load cell (LC) outputs, each LC output has an uncertainty and is correlated to the others. i.e. cal(6,1)*LC1 + cal(6,2)*LC2 + cal(6,3)*LC3 + cal(6,4)*LC4 + ... 
As before when I run this line independently no error is raised.
Also I had to push "continue" on the debugger 5 times before the code moves onto evaluating the following operations. It pauses again in the next loop on a simple subtraction of two values. 
![Screen Shot 2020-11-02 at 8 08 23 PM](https://user-images.githubusercontent.com/33333375/97935647-38565e80-1d47-11eb-945a-db6c353f85df.png)

```
Error in as.environment(pos) : invalid 'pos' argument
In addition: Warning messages:
1: In rm(list = id, pos = ht[[var]]) :
  object '<environment: 0x11233d0d0>' not found
2: In rm(list = id, pos = ht[[var]]) :
  object '<environment: 0x112085c70>' not found
3: In rm(list = id, pos = ht[[var]]) :
  object '<environment: 0x1124dae30>' not found
4: In rm(list = id, pos = ht[[var]]) :
  object '<environment: 0x1069c0ae8>' not found
5: In rm(list = id, pos = ht[[var]]) :
  object '<environment: 0x10e43dd10>' not found
6: In rm(list = id, pos = ht[[var]]) :
  object '<environment: 0x10cfc2720>' not found
7: In rm(list = id, pos = ht[[var]]) :
  object '<environment: 0x10c179630>' not found
Called from: rm(list = id, pos = ht[[var]])
Browse[1]> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.15.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] phonTools_0.2-2.1 quantities_0.1.2  units_0.6-2       pracma_2.1.4      R.matlab_3.6.1   
[6] errors_0.3.5     

loaded via a namespace (and not attached):
[1] compiler_3.4.1    tools_3.4.1       curl_2.7          Rcpp_1.0.1        remotes_2.2.0    
[6] R.methodsS3_1.7.1 R.utils_2.5.0     R.oo_1.21.0   
```

**Comment by Enchufa2** [comment]
The R version is quite old. Do you have access to a more recent version to see whether the problem persists?

**Comment by charvey23** [comment]
Interestingly it was the RStudio version that seemed to be causing the problem. I first updated the R version and the error still occurred but once updating RStudio it has now gone away! Thank you for your time.

**Comment by Enchufa2** [comment]
Wow, really? What a strange issue! Glad you managed to solve it! Out of curiosity... what was the RStudio version? Does the CRAN version of `errors` work without issue now?

**Comment by charvey23** [comment]
Unfortunately I didn't note the RStudio version before updating but it would have been from sometime in 2017. I just checked and the CRAN version does work without error!

**Comment by Enchufa2** [comment]
Great, thanks!
