### ISSUE TITLE
The errors will be removed/striped when using melt() and dcast().

### ISSUE THREAD

**Issue by yu-soong** [r-quantities/errors#46]
The errors will be removed after melt() or dcast(), no matter it is reshape2::melt() or melt.data.table(). 

By the way, It seems the *errors* package works well in data.table, not for the melt() and dcast() functions though. So make it work for the function melt() would be great!

**Comment by Enchufa2** [comment]
No, it doesn't work with `data.table`. To achieve maximum performance, `data.table` has its own code to wrangle data, and thus it doesn't call the methods that this package provides for `errors` objects. Therefore, it's not in our hand to make it work. I suggest to use base R methods to work with `errors`, `units` or `quantities` objects. There is some support for `dplyr` too thanks to `vctrs`, but it's not 100%.

**Comment by yu-soong** [comment]
Ok then I'll use `dplyr` with `errors`. Thanks
