### ISSUE TITLE
Add to awesome list?

### ISSUE THREAD

**Issue by krlmlr** [r-quantities/errors#49]
The errors class would be a good fit for https://github.com/krlmlr/awesome-vctrs#readme, would you like to contribute?

**Comment by Enchufa2** [comment]
Great, do you mind if I send [quantities](https://github.com/r-quantities/quantities) in the same PR?

**Comment by krlmlr** [comment]
Not at all, thanks!

**Comment by krlmlr** [comment]
Done, thanks again!
