### ISSUE TITLE
sum() function and errors propagation

### ISSUE THREAD

**Issue by JorgeMonPe** [r-quantities/errors#51]
Hi,
First at all, thanks you for this really useful package!

I don't understand very well why I don't get the same error when a use the sum() R base function and summing each element separately:

```
n <- set_errors(2.21, 0.87)
drop_errors(n+n+n+n+n+n+n+n+n+n)
[1] 22.1
errors_min(n+n+n+n+n+n+n+n+n+n)
[1] 13.4

#But if I use sum() function
drop_errors(sum(rep(n, length.out = 10)))
[1] 22.1
errors_min(sum(rep(n, length.out = 10)))
[1] 19.34882
```
Why in first case I get 13.4 as min error and in the second one I get 19.35? 
Is any difference in errors calculation?

**Comment by Enchufa2** [comment]
Yes, there's a difference. In the first case, you are adding up the same vector 10 times, which is correlated with itself. In the second case, you are summing uncorrelated values of a vector of size 10.

**Comment by JorgeMonPe** [comment]
Ok!, Thank you very much!
