### ISSUE TITLE
While dropping rows from data.table, it doesn't drop the corresponding errors, hence errors shift

### ISSUE THREAD

**Issue by onurcanbektas** [r-quantities/errors#53]
Consider the following dataset

`structure(list(X = c(184, 185, 186, 187), Y = c(11, 11, 11, 11
), speed = structure(c(0.452321422470924, 0.72069857430722, 0.0368680229919084, 
46.3109219437881), id = <environment>, errors = c(0.0573882051516185, 
0.0914385115984206, 0.0046776242775241, 5.87569050953262), class = "errors"), 
    region_ID = c(0, 0, 0, 0), distance = c(20, 20, 20, 20), 
    px_to_um = c(1.96969700324073, 1.96969700324073, 1.96969700324073, 
    1.96969700324073), frame_to_seconds = structure(c(0.021766275, 
    0.021766275, 0.021766275, 0.021766275), id = <environment>, errors = c(0.00276159251592122, 
    0.00276159251592122, 0.00276159251592122, 0.00276159251592122
    ), class = "errors")), row.names = c(NA, -4L), class = c("data.table", 
"data.frame"), .internal.selfref = <pointer: 0x7f8f8b80bee0>)`

The errors of the `speed` column are 
![image](https://user-images.githubusercontent.com/18240112/172139398-fd58a253-0215-4dda-bd4a-75e6ecb99432.png)

but when some of the rows are dropped
`b<-a[2,3]`
we get
![Screenshot 2022-06-06 at 11 58 43](https://user-images.githubusercontent.com/18240112/172139505-b3672883-b561-4dc8-94e4-b5c79cd149f2.png)

**Comment by r2evans** [comment]
FYI, your sample data is not perfectly consumable while it includes `<environment>` and `<pointer:*>` in the structure. It's not hard for others to remove it, but it shouldn't really be there in the first place (not to mention that the images of your data do not show `id`, so ... not sure why your data and your pic-of-data differ thus).

**Comment by Enchufa2** [comment]
Thanks for the report, and thanks @r2evans for your comments. Indeed, `errors` work fine with dataframes because we implement all the subsetting methods:

``` r
iris[1:4] <- lapply(iris[1:4], function(x) errors::set_errors(x, x*0.01))
iris[2, 3]
#> 1.40(1)
iris[c(2, 3), ]
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 2      4.90(5)     3.00(3)      1.40(1)    0.200(2)  setosa
#> 3      4.70(5)     3.20(3)      1.30(1)    0.200(2)  setosa
```

It works fine also with tibbles and `dplyr` workflows thanks to `vctrs`.

`data.table` does its own thing when it comes to subsetting. In particular, it doesn't support vectorised attributes, and unfortunately there is nothing we could do about it, sorry.
