### ISSUE TITLE
NA handling in mean(na.rm=T)

### ISSUE THREAD

**Issue by ekatko1** [r-quantities/errors#56]
Thanks for the awesome package!

Currently, 

```
> c(NA, 1, 2) %>% set_errors(0) %>% mean(na.rm = T)
1.5(NA)
```

So `na.rm=T` does not work for errors. 

As a workaround, one needs to do something like this:

```
> c(NA, 1, 2) %>% na.omit() %>% set_errors(0) %>% mean(na.rm = T)
1.5(5)
```

**Comment by Enchufa2** [comment]
Good catch! In fact, there's the same issue in several summaries. Thanks for the report.
