### ISSUE TITLE
Error in mean calculations

### ISSUE THREAD

**Issue by mone27** [r-quantities/errors#57]
I starting to use the errors library and realized that there are small inaccuriacies in the calculation of the mean.
I'd expect that the mean is the same both if you have the errors and if you don't. However this is not the case there in this scenario.

``` r
library(errors)
x <- c(608.36,352.72,173.34,368.29,321.81,436.48,487.58,592.63,352.69,567.77)
errors(x) <- c(121.672, 70.544, 34.668, 73.658, 64.362, 87.296, 97.516, 118.526, 70.538, 113.554)
drop_errors(x) |> mean()
#> [1] 426.167
mean(x)
#> 430(90)
```
am I missing something or there is actually an issue in the library?
<sup>Created on 2023-04-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Enchufa2** [comment]
The result is the same, but error formatting rounds properly to 1 error digit by default. If you want to report a more precise error, you need to specify it:

```r
print(mean(x), digits=5)
#> 426.167(85233)
```

**Comment by Enchufa2** [comment]
Thanks for the report. Closing here if there are no further issues.

**Comment by mone27** [comment]
ah ok! thanks for the explanation!
