### ISSUE TITLE
scientific=FALSE format not always respected

### ISSUE THREAD

**Issue by nstjhp** [r-quantities/errors#62]
Thank you for this very nice package. I wish to share some data with non-mathematical collaborators who can't handle scientific notation i.e. `10e6` etc, but conveniently `?format.errors` tells me we can turn this format off. However if the numbers get too large, it seems this does not work. I made a minimal reprex to highlight the issue. It shows that the format options are respected when the value is `< 10e5`, but once we are `>= 10e5` the scientific notation comes back even when `scientific=FALSE`. Is there some other option I can set to get "normal" printing format within a tibble?

``` r
library(tidyverse)
library(errors) # version 0.4.1

z = as_tibble_col(set_errors(c(99999.999, 100000), 1:2*10000 * 0.05))
z
#> # A tibble: 2 × 1
#>         value
#>         (err)
#> 1 100000(500)
#> 2   1.00(1)e5
z |> mutate(format(value, digits=6))
#> # A tibble: 2 × 2
#>         value `format(value, digits = 6)`
#>         (err) <chr>                      
#> 1 100000(500) 99999.999(500000)          
#> 2   1.00(1)e5 1.0000000(100000)e5
z |> mutate(format(value, scientific=TRUE))
#> # A tibble: 2 × 2
#>         value `format(value, scientific = TRUE)`
#>         (err) <chr>                             
#> 1 100000(500) 10.00(5)e4                        
#> 2   1.00(1)e5 1.00(1)e5
z |> mutate(format(value, scientific=FALSE))
#> # A tibble: 2 × 2
#>         value `format(value, scientific = FALSE)`
#>         (err) <chr>                              
#> 1 100000(500) 100000(500)                        
#> 2   1.00(1)e5 1.00(1)e5 <--------------------  should not use e5 here
z |> mutate(format(value, notation="plus-minus"))
#> # A tibble: 2 × 2
#>         value `format(value, notation = "plus-minus")`
#>         (err) <chr>                                   
#> 1 100000(500) 100000 ± 500                            
#> 2   1.00(1)e5 (1.00 ± 0.01)e5
```

<sup>Created on 2024-08-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by Enchufa2** [comment]
The `scientific` flag (disabled by default) allows you to easily switch to scientific notation. If this is not enabled, then the usual R formatting following the `scipen` option applies. So, if you set, for instance, `options(scipen = 999)`, you get what you are looking for.

**Comment by nstjhp** [comment]
Thanks for the swift reply, you are right, I should have known about this `scipen` option. It works as you said!
